apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-crud-app
  template:
    metadata:
      labels:
        app: go-crud-app
    spec:
      containers:
      - name: go-crud-app
        image: firemanm/go-crud-app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: go-crud-app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: go-crud-app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: go-crud-app-config
              key: DB_NAME
        - name: DB_SSLMODE
          valueFrom:
            configMapKeyRef:
              name: go-crud-app-config
              key: DB_SSLMODE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: go-crud-app-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: go-crud-app-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-crud-app-secret
              key: DB_PASSWORD
