apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-crud-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: go-crud-app-svc
            port:
              number: 80