{
 "title": "Filtering by method",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "api_method",
    "query": {
     "query": "label_values(gocrudapp_http_request_duration_seconds_bucket,method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (rate(gocrudapp_http_request_duration_seconds_bucket{method=\"$api_method\"}[5m])))",
     "legendFormat": "{{method}} - q0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(gocrudapp_http_request_duration_seconds_bucket{method=\"$api_method\"}[5m])))",
     "legendFormat": "{{method}} - q0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(gocrudapp_http_request_duration_seconds_bucket{method=\"$api_method\"}[5m])))",
     "legendFormat": "{{method}} - q0.99"
    },
    {
     "expr": "max by(method) (rate(gocrudapp_http_request_duration_seconds_sum{method=\"$api_method\"}[5m])) / (max by(method) (rate(gocrudapp_http_request_duration_seconds_count[5m])))",
     "legendFormat": "{{method}} - qMAX"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(gocrudapp_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "q99 total"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le, method) (rate(gocrudapp_http_requests_total{method=\"$api_method\"}[5m]))",
     "legendFormat": "{{method}} - q0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(gocrudapp_http_request_duration_seconds_bucket{method=\"$api_method\"}[5m])))",
     "legendFormat": "{{method}} - q0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(gocrudapp_http_request_duration_seconds_bucket{method=\"$api_method\"}[5m])))",
     "legendFormat": "{{method}} - q0.99"
    },
    {
     "expr": "max by(method) (rate(gocrudapp_http_request_duration_seconds_sum{method=\"$api_method\"}[5m])) / (max by(method) (rate(gocrudapp_http_request_duration_seconds_count[5m])))",
     "legendFormat": "{{method}} - qMAX"
    }
   ]
  },
  {
   "title": "ERROR Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(gocrudapp_http_requests_total{statuscode=\"500\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}